version: '3' 
services: 
    data-pipeline:
        container_name: data-pipeline 
        build: .
        image: energytrading/data-pipeline:latest
        restart: always
        env_file:
            - .env 
        volumes: 
            - .:/app 
        depends_on: 
            timescaledb:
                condition: service_healthy
        networks: 
            - network  
    timescaledb:
        container_name: timescaledb 
        image: timescale/timescaledb:latest-pg14
        restart: always 
        env_file:
            - .env 
        ports: 
            - "5432:5432"
        volumes: 
            - tsdb-volume:/var/lib/postgresql/data
            - ./init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh
        healthcheck:
            test: ["CMD", "pg_isready", "-U", $POSTGRES_USER, "-d", $POSTGRES_DB]
            interval: 30s
            timeout: 10s
            retries: 5
        networks: 
            - network
volumes:
  tsdb-volume:
networks: 
    network: 